### PR TITLE
pip < 6.0 compatibility

### PR DESCRIPTION
**Pull request by rvause**
First pass at fixing test case added in #3

### CODE REVIEW

**Comment by rvause** [comment]
Of course, I think [this](https://github.com/jgonggrijp/pip-review/pull/1#issuecomment-158761760) comment makes sense and perhaps it would be preferable to depend on `packaging` make this issue go away in a somewhat permanent way.

**Comment by jgonggrijp** [comment]
Hi @rvause, thanks for working on this and happy new year. :-)

Is it your intention to restore pip<6.0 compatibility and make the corresponding test succeed? Is this something you are still working on?

**Comment by rvause** [comment]
Though this fixes the `ImportError` from [this build](https://travis-ci.org/jgonggrijp/pip-review/builds/95425573) and fixes #2, there still remains an issue with that test case (apparently `wheel` and `six` are not expected) - possibly an issue with the test.

With that aside I think it would be more suitable to close this PR and go the route of adding `packaging` as a dependency avoiding the use of the `vendor` module in pip itself given that it has been subject to change in the past.

**Comment by jgonggrijp** [comment]
I agree. I will close the pull request for now, but it can be reopened if we change our minds.

**Pull request closed without merging**
