### PR TITLE
test(review.t): fix for Windows

### PR DESCRIPTION
**Pull request by 5j9**
Use prysk and make a bunch of other changes that make the tests pass on Windows.

### CODE REVIEW

**Comment by 5j9** [comment]
Apparently [prysk only supports Python 3.7+](https://github.com/Nicoretti/prysk/blob/950dc4c07cb2068d48050177c3f2b532c2bce891/pyproject.toml#L58) :/

**Comment by jgonggrijp** [comment]
Ah. I appreciate the effort, but I'm afraid anything based on `cram` is a dead end. Especially if it doesn't support Python<3.7, because we may need to keep a support branch for 1.x open for a while.

Would you be interested in taking up the challenge on #61?

**Comment by 5j9** [comment]
I thought about a line-by-line translation of existing tests to pytest, but I think the result would be more verbose and less readable than cram style. Maybe I'll give it another shot later, no promises.

**Comment by jgonggrijp** [comment]
Yeah, feel free to organize the pytest setup very differently from the cram setup.

Honestly, I think the cram file was too compact to be true.

**Pull request closed without merging**
