### PR TITLE
Add windows compatibility

### PR DESCRIPTION
**Pull request by xoviat**
Simple, really.

### CODE REVIEW

**Comment by jgonggrijp** [comment]
I will need to review this. Currently, your patch breaks the build test, so I cannot accept it.

If somebody else can confirm that pip-review currently doesn't work on Windows, that would be nice.

**Comment by xoviat** [comment]
I created a new pip package called "pip-review-win" until this is pushed into production. I am not exactly sure why the build is failing. The only change I made was to add a script to setup.py

**Comment by xoviat** [comment]
Also, the only change here is to add a BAT file that calls pip-review. This is because windows does not support the shebang.

**Comment by jgonggrijp** [comment]
I have now released [version 0.5](https://pypi.python.org/pypi/pip-review/0.5), which uses [a more intelligent way to generate the script](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/). This should be compatible with Windows. You can retract pip-review-win from PyPI if you wish. :-)

**Pull request closed without merging**
