### PR TITLE
Fixes #10

### LINKED ISSUE #10: mysql-connector-python==2.0.4 is available (you have 2.1.3)
Hello

Today I use pip-review for first time.
I updated several packets successfully. Thanks to dev :)
But it remains a wonder that dilemma (I am under ARM Archlinux).
$ pip-review
mysql-connector-python==2.0.4 is available (you have 2.1.3)

It's normal?

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**

### CODE REVIEW

**Comment by jgonggrijp** [comment]
Thanks for the fix!

**Comment by bil-elmoussaoui** [comment]
If you need me again just ping me ;)

**Comment by jgonggrijp** [comment]
If that is not a joke, please take a look at #15, the [feature/python3](https://github.com/jgonggrijp/pip-review/tree/feature/python3) branch and 9c6a53a. ;-)

In general, I need you and everyone else for any issue that has the "help wanted" tag.

**Comment by bil-elmoussaoui** [comment]
I would definitely send more PR in the future ;) you can join me on tg @bilelmoussaoui

**Pull request merged**
